# Config file for shopify project, dev, that I worked on at shopify
# check it out at github.com/shopify/dev

up:
  - ruby: 2.3.1
  - bundler

commands:
  build: ruby generate.rb && git add index.html && git commit -m "generated index.html" && open index.html

open:
  site: http://kpeng.ca
  admin: https://analytics.google.com/analytics/web/?authuser=0#realtime/rt-traffic/a82837659w122463402p128135112/
