\documentclass[letterpaper]{kevin-resume} 

\begin{document}
\namesection{Kevin}{Peng}{
Software Engineering Student at University of Waterloo\\
ktpeng@uwaterloo.ca \\
kpeng.ca \textbullet{}  github.com/kevintpeng  \textbullet{}  linkedin.com/in/kevintpeng\\ 
}

\begin{minipage}[t]{0.8\textwidth}


\section{Summary of Qualifications}
\sectionspace
\begin{tightitemize}
\item 
\item Full stack web developer with backend experience in Ruby on Rails and SQL databases and frontend experience in HTML, CSS and JavaScript.
\item Experience in building desktop applications in Java, Python, C and C++.
\item Unix user and user of git version control.
\item Passionate designer, several years of Photoshop experience for digital painting and graphics design.
\end{tightitemize}
\sectionspace

\section{WORK EXPERIENCE}

\runsubsection{Shopify}
\descript{| Production Engineering Intern}
\location{Ottawa ON | May 2016-August 2016}
\sectionspace
\runsubsection{Petro Recruit}
\descript{| Technical Co-founder}
\location{Calgary AB / Waterloo ON | August 2015-Current}
\begin{tightitemize}
\item Built a recruiting platform, with over 3000 job postings and 1500+ active users.
\item Launched the Ruby on Rails app on Heroku with Elasticsearch implemented. Link: petrorecruit.co
\item Developed a web crawler and scraper
%\item Balanced a 20 hour per week work schedule in addition to a full course load.
\end{tightitemize}
\sectionspace % Some whitespace after the section

%------------------------------------------------

\runsubsection{Velocity Garage}
\descript{| PetroPredict, Software Engineering Intern}
\location{Waterloo ON | June 2014-August 2014}
\begin{tightitemize}
\item Built a data processor (Python) that sanitized billions of data entries.
\item Optimized existing sanitation process to be more than 20 times faster.
%\item Designed frontend interface and user experience for a django application.
\item Created graphical visualizions of JSON data with JavaScript and d3.js.
%\item Designed company banner with Photoshop.
%\item Published an article on the University of Waterloo's Velocity website about my work term: http://velocity.uwaterloo.ca/2014/08/student-experiences-startup-life/
\end{tightitemize}
\sectionspace % Some whitespace after the section

\section{Projects}

\runsubsection{Java desktop application}
\descript{| Rubik's Cube Solver}
\begin{tightitemize}
\item A Rubik's cube application that can display and solve any scramble.
\item Average solve time is 98 quarter-turns, in less than a second.
\end{tightitemize}
\sectionspace

\runsubsection{Ruby on Rails web application}
\descript{| UW Overflow}
\begin{tightitemize}
\item Ruby on Rails application that implements a voting-based system for crowd-sourced answers and collaboration on practice exams and homework.
\end{tightitemize}
\sectionspace

\runsubsection{Python desktop application}
\descript{| Dota 2 Drafter and Statistical Analyzer}
\begin{tightitemize}
\item Scrapes and processes data from the Dota 2 API, and aggregates data from millions of matches.
\item Sorts heroes based on statistical success against the opposing team.
\end{tightitemize}
\sectionspace

%------------------------------------------------
% Education
%------------------------------------------------

\section{Education} 

Candidate for Bachelor of Software Engineering at University of Waterloo, 2020

\sectionspace % Some whitespace after the section


%------------------------------------------------
% Awards
%------------------------------------------------

%\section{AWARDS \& DISTINCTIONS} 

%Canada-wide Science Fair Silver Medalist and Best in Category of Information (\$3200)\\
%3x Gold Medalist for Waterloo-Wellington Science and Engineering Fair (\$300)\\
%Eastern Canada Student Energy Conference Innovation Award (\$500)\\
%\sectionspace % Some whitespace after the section



%----------------------------------------------------------------------------------------

\end{minipage} % The end of the right column

\end{document}
